name: CRON
on:
    schedule:
      - cron: '0 22 * * *'
jobs:
  cron:
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.4.1]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1.0
      - name: Update data/daily.tsv
        env:
            PGHOST: localhost
            PGPORT: ${{ job.services.postgres.ports[5432] }}
            PAT: ${{ secrets.PAT }}
        run: julia --proj -e 'using Pkg; Pkg.instantiate(); using COVID_Tracking_Clean; COVID_Tracking_Clean.main()'
